### ISSUE TITLE
Standardize return of isobar and isopleth calculation

### ISSUE THREAD

**Issue by kaylai** [kaylai/MagmaSatPlus#19]
This becomes really important when comparing model results and plotting.

**Comment by kaylai** [comment]
Simon, we should discuss the best way to do this. I don't have a strong preference but need to logic it out. I went to do some plotting comparing isobars from different models and realized the plotting was not straightforward since MagmaSat and non-MagmaSat models return data in different ways. 

The MagmaSat model is currently returning two pandas dataframes, mostly because this made sense in my head as to how to go about it, but I could certainly be convinced to change this to something simpler!  Non-MagmaSat MixedFluids models return two lists; is this returned inside a tuple? Curious as to why `return (isobars, isopleths)` instead of `return isobars, isopleths`.

One options is to change MagmaSat to mimic the non-MagmaSat return, and then add a verbose option (currently not implemented) that would return one or two pandas dataframes (basically the current return). This will make more or less sense depending on how I implement the save_excelfile() method, so I will go work on that now! `</ramble>`

**Comment by simonwmatthews** [comment]
I think returning dataframes is the more elegant and user-friendly way of doing this. The only reason I implemented the list of arrays is because it made feeding into my testing routines very straightforward. I think the best way forward is for me to modify the MixedFluids method to provide the same output as the MagmaSat method.

**Comment by simonwmatthews** [comment]
Implemented.
