### ISSUE TITLE
Standardize calcuate_degassing_paths() methods

### ISSUE THREAD

**Issue by kaylai** [kaylai/MagmaSatPlus#20]
Simon, based on your email it sounds like the best way forward is for you to reformat your degassing paths methods to be more like MagmaSat. I'll assign this issue to you for now, but please let me know if I can tweak things, too.

**Comment by kaylai** [comment]
Will change 'system' argument to 'fractionate_vapor' allowing values of 0 to 1 at first, then adjusting code to allow any value, where 0.5 keeps half of the vapor and removes the other half. will add pressure argument, where default is just to start at saturation. If a value is passed, will start from that value instead.

**Comment by kaylai** [comment]
@simonwmatthews Question! Does 'fractionate_vapor' refer to how much vapor is _retained_ at each pressure step or how much vapor is _removed_ at each pressure step? I'm currently coding MagmaSat such that the default value is fractionate_vapor=1.0, which is a closed system where all vapor is retained from one step to the next.

**Comment by kaylai** [comment]
Done! Just need to make sure I am using the 'fractionate_vapor' variable correctly (re: my previous comment), but the MagmaSat function now works! I've added some test examples to the manuscript as well. Will push those changes now.

**Comment by simonwmatthews** [comment]
> @simonwmatthews Question! Does 'fractionate_vapor' refer to how much vapor is _retained_ at each pressure step or how much vapor is _removed_ at each pressure step? I'm currently coding MagmaSat such that the default value is fractionate_vapor=1.0, which is a closed system where all vapor is retained from one step to the next.

The variable is how much vapour is removed, i.e. 1.0 = open system, 0.0 = closed system. I tried to make it analogous to the fractionation coefficients in MELTS (e.g. https://enki-portal.gitlab.io/ThermoEngine/MELTS-v1.0.2-fractionation.html).

**Comment by kaylai** [comment]
Implemented! @simonwmatthews I have changed the default for both of our models to be 0.0 (closed-system). Is that okay with you? It makes the most sense to me, but if you have a reason for having it the other way, I am open to that!
