### ISSUE TITLE
Allow import of module without thermoengine, if MagmaSat methods are not being used.

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/MagmaSatPlus#27]
I *think* an easy way of doing this is to have a bool statement before thermoengine is imported, which someone can configure in the python module file directly, if they are using it without thermoengine. I don't think this will cause any errors, unless thermoengine is specifically called.

However, I suspect there's a much more clever way of doing this.

The reason I think this is useful is for if people want to incorporate solubility code into other models (I've done this in the past, and is what my code was originally developed for...).

What are your thoughts? No urgency to doing this.

**Comment by kaylai** [comment]
Question: what if we simply put the import in the __init__ method of MagmaSat and ExcelFile?

**Comment by simonwmatthews** [comment]
> Question: what if we simply put the import in the **init** method of MagmaSat and ExcelFile?

That sounds better! The only issue I see with that is in the default_models dictionary- instances of each model are initialised here when the module is imported. I've fixed this by removing magmasat from the default_models dictionary, and checking for the model='magmasat' before the "if type(model) == str:" in Calculate.__init__(). This will appear in my next push. I'll leave you to move the import thermoengine command as you're much more familiar with the MagmaSat and ExcelFile methods!

**Comment by kaylai** [comment]
Implemented. Note that this implementation might make individual magmasat calculations slower. In future, should see if this can be more selectively imported or if there is a way to speed it up.
