### ISSUE TITLE
MixedFluids can't take X_fluid as float

### ISSUE THREAD

**Issue by kaylai** [kaylai/MagmaSatPlus#49]
Example:

`m.calculate_dissolved_volatiles(sample=bulk_comp, temperature=900.0, pressure=2000.0, 
                                X_fluid=0.5, model='Dixon').result`
<img width="998" alt="Screen Shot 2020-05-20 at 1 37 45 PM" src="https://user-images.githubusercontent.com/6538370/82484142-1f126c00-9a9f-11ea-83ee-63376721638b.png">

**Comment by simonwmatthews** [comment]
Fixed. X_fluid can now be a float or int.
