### ISSUE TITLE
How to return data?

### ISSUE THREAD

**Issue by kaylai** [kaylai/MagmaSatPlus#7]
The MagmaSat single-sample calculations return dictionaries. This was chosen because of the usage of the "verbose" argument. When verbose==True, a dictionary with lots of useful data is returned. Due to the large number of values returned, a dictionary makes the most sense for this case. When verbose==False, a simple dictionary is returned (consistent with verbose=True).

Non MagmaSat methods currently return series (value, value). Can we make these return dicts? Is this the best solution?

**Comment by simonwmatthews** [comment]
DataFrames are now the default output for calculate_degassing_paths and calculate_isobars_and_isopleths.
