### ISSUE TITLE
Instance type for X_fluid argument?

### ISSUE THREAD

**Issue by kaylai** [kaylai/MagmaSatPlus#8]
Currently non-MagmaSat models require two values passed as, e.g., X_fluid=(0.5,0.5). I assume this is (H2Ofluid, CO2fluid)? If so, isn't this redundant and we could simply pass one float? The MagmaSat model currently takes X_fluid as one float (X_fluid=0.5).

**Comment by simonwmatthews** [comment]
The reason I formatted X_fluid this way was to allow for adding additional components to the fluid in the future, e.g. SO2. However, it is redundant for a two-component fluid. One way to preserve this feature (if we do want to preserve it- I'm not sure we do) would be to allow both X_fluid=0.5 and X_fluid=(0.5,0.5) to be passed to the functions for the case where its a two-component fluid.

**Comment by kaylai** [comment]
Ah, that makes sense! I love your forward thinking. Adding sulfur to this is a definite (future) goal, and I like the idea of keeping things extensible. MagmaSat won't likely be extensible for this use case, unfortunately. I think allowing the non-MagmaSat methods to accept either X_fluid=0.5 or X_fluid=(0.5,0.5) is a good way forward. For MagmaSat, I'll leave it as only accepting X_fluid=0.5.

**Comment by simonwmatthews** [comment]
MixedFluids can now receive X_fluid as a float when there are two volatile species.
